import { Target } from '../../types/index';
import { logger } from '../utils';
import { ErrorLog } from '../../types/index';

export const attemptExploit = async (target: Target, key: string): Promise<boolean> => {
    logger.info(`Module [Exploit]: Attempting breach on ${target.ip} on ports [${target.ports.join(', ')}]...`);
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Mock logic with a 50% success rate
    const success = Math.random() > 0.5;
    
    if (success) {
        logger.info(`Module [Exploit]: SUCCESS - Gained access to ${target.ip}.`);
    } else {
        logger.warn(`Module [Exploit]: FAILED - Could not breach ${target.ip}.`);
    }

    return success;
};

// Provides context for the last failed attempt
export const getLastError = (): Omit<ErrorLog, 'targetIp'> => {
    return { type: 'conn_fail', details: 'Port refused or firewall block.' };
};
